
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'adventure_works_analytics'
version: '1.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'adventure_works_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  adventure_works_analytics:
    # Config indicated by + and applies to all files under models/example/
    commercial:
      +database: commercial
      +tags: crm
      staging: &staging
        +materialized: ephemeral
      intermediate: &intermediate
        +materialized: ephemeral
      marts: &marts
        +materialized: table

    projects:
      +database: projects
      +tags: projects
      staging: *staging
      intermediate: *intermediate
      marts: *marts

    people:
      +database: people
      +tags: people
      staging: *staging
      intermediate: *intermediate
      marts: *marts

    bi-tool:
      +enabled: false

# Seeds configuration
seeds:
  adventure_works_analytics:
    commercial:
      +database: commercial
      +tags: crm
      +schema: raw_sheets
    people:
      +database: people
      +tags: people
      +schema: raw_sheets

# Snapshots configuration
snapshots:
  adventure_works_analytics:
    +target_schema: snapshots