dbt_indicium:
  target: "{{ env_var('DBT_PROFILE_TARGET', 'dev') }}"
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SF_DB_ACCOUNT') }}"
      user: "{{ env_var('DBT_SF_DEV_USER') }}"
      password: "{{ env_var('DBT_SF_DEV_PASSWORD') }}"
      role: "{{ env_var('DBT_SF_DEV_ROLE') }}"
      database: "{{ env_var('DBT_SF_DEV_DATABASE') }}"
      warehouse: "{{ env_var('DBT_SF_DEV_WAREHOUSE') }}"
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"
      threads: 2
      client_session_keep_alive: False
      # query_tag: [anything]
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false
    ci:
      type: snowflake
      account: "{{ env_var('DBT_SF_ACCOUNT') }}"
      user: "{{ env_var('DBT_SF_CI_USER') }}"
      password: "{{ env_var('DBT_SF_CI_PASSWORD') }}"
      role: "{{ env_var('DBT_SF_CI_ROLE') }}"
      database: "{{ env_var('DBT_SF_CI_DATABASE') }}"
      warehouse: "{{ env_var('DBT_SF_CI_WAREHOUSE') }}"
      schema: "{{ env_var('DBT_SF_CI_SCHEMA') }}"
      threads: 2
      client_session_keep_alive: False
      # query_tag: [anything]
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false